### ISSUE TITLE
Update PyPI with the new version (to support python 3)

### ISSUE THREAD

**Issue by rwarren** [aivuk/formcreator#8]
I just installed with `pip install formcreator` to try this library out. The first demo immediately failed on an import of the long-deprecated `sha` module.

It looks like this has been fixed, and python3 is supported,  since https://github.com/aivuk/formcreator/commit/59824649475a7b6a4234885f42de6a7ccfe50e22 (committed on 2017-07-17!).

This should really be uploaded to PyPI so that pip installs work directly, and direct-from-git workarounds like this are not required:

```
pip install git+git://github.com/aivuk/formcreator.git@219cf2ec83d05f2c1c743f42f33716a515c0a13b
```

**Comment by aivuk** [comment]
Thanks for letting me know about it. I released a new version on PyPI according to your suggestion. :+1:
